using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;

// Token: 0x02000433 RID: 1075
internal sealed class Class491
{
	// Token: 0x060017AE RID: 6062 RVA: 0x000644C8 File Offset: 0x000626C8
	public static List<Class647> smethod_0()
	{
		List<Class647> list = new List<Class647>();
		foreach (object obj in Regex.Matches("\r\nDeployment Image Servicing and Management tool\r\nVersion: 10.0.19041.3636\r\n\r\nImage Version: 10.0.19045.4412\r\n\r\nFeatures listing for package : Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.19041.1\r\n\r\nFeature Name : TFTP\r\nState : Disabled\r\n\r\nFeature Name : LegacyComponents\r\nState : Disabled\r\n\r\nFeature Name : DirectPlay\r\nState : Disabled\r\n\r\nFeature Name : SimpleTCP\r\nState : Disabled\r\n\r\nFeature Name : Windows-Identity-Foundation\r\nState : Disabled\r\n\r\nFeature Name : NetFx3\r\nState : Enabled\r\n\r\nFeature Name : WCF-HTTP-Activation\r\nState : Disabled\r\n\r\nFeature Name : WCF-NonHTTP-Activation\r\nState : Disabled\r\n\r\nFeature Name : IIS-WebServerRole\r\nState : Disabled\r\n\r\nFeature Name : IIS-WebServer\r\nState : Disabled\r\n\r\nFeature Name : IIS-CommonHttpFeatures\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpErrors\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpRedirect\r\nState : Disabled\r\n\r\nFeature Name : IIS-ApplicationDevelopment\r\nState : Disabled\r\n\r\nFeature Name : IIS-Security\r\nState : Disabled\r\n\r\nFeature Name : IIS-RequestFiltering\r\nState : Disabled\r\n\r\nFeature Name : IIS-NetFxExtensibility\r\nState : Disabled\r\n\r\nFeature Name : IIS-NetFxExtensibility45\r\nState : Disabled\r\n\r\nFeature Name : IIS-HealthAndDiagnostics\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpLogging\r\nState : Disabled\r\n\r\nFeature Name : IIS-LoggingLibraries\r\nState : Disabled\r\n\r\nFeature Name : IIS-RequestMonitor\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpTracing\r\nState : Disabled\r\n\r\nFeature Name : IIS-URLAuthorization\r\nState : Disabled\r\n\r\nFeature Name : IIS-IPSecurity\r\nState : Disabled\r\n\r\nFeature Name : IIS-Performance\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpCompressionDynamic\r\nState : Disabled\r\n\r\nFeature Name : IIS-WebServerManagementTools\r\nState : Disabled\r\n\r\nFeature Name : IIS-ManagementScriptingTools\r\nState : Disabled\r\n\r\nFeature Name : IIS-IIS6ManagementCompatibility\r\nState : Disabled\r\n\r\nFeature Name : IIS-Metabase\r\nState : Disabled\r\n\r\nFeature Name : WAS-WindowsActivationService\r\nState : Disabled\r\n\r\nFeature Name : WAS-ProcessModel\r\nState : Disabled\r\n\r\nFeature Name : WAS-NetFxEnvironment\r\nState : Disabled\r\n\r\nFeature Name : WAS-ConfigurationAPI\r\nState : Disabled\r\n\r\nFeature Name : IIS-HostableWebCore\r\nState : Disabled\r\n\r\nFeature Name : WCF-Services45\r\nState : Enabled\r\n\r\nFeature Name : WCF-HTTP-Activation45\r\nState : Disabled\r\n\r\nFeature Name : WCF-TCP-Activation45\r\nState : Disabled\r\n\r\nFeature Name : WCF-Pipe-Activation45\r\nState : Disabled\r\n\r\nFeature Name : WCF-MSMQ-Activation45\r\nState : Disabled\r\n\r\nFeature Name : WCF-TCP-PortSharing45\r\nState : Enabled\r\n\r\nFeature Name : IIS-StaticContent\r\nState : Disabled\r\n\r\nFeature Name : IIS-DefaultDocument\r\nState : Disabled\r\n\r\nFeature Name : IIS-DirectoryBrowsing\r\nState : Disabled\r\n\r\nFeature Name : IIS-WebDAV\r\nState : Disabled\r\n\r\nFeature Name : IIS-WebSockets\r\nState : Disabled\r\n\r\nFeature Name : IIS-ApplicationInit\r\nState : Disabled\r\n\r\nFeature Name : IIS-ASPNET\r\nState : Disabled\r\n\r\nFeature Name : IIS-ASPNET45\r\nState : Disabled\r\n\r\nFeature Name : IIS-ASP\r\nState : Disabled\r\n\r\nFeature Name : IIS-CGI\r\nState : Disabled\r\n\r\nFeature Name : IIS-ISAPIExtensions\r\nState : Disabled\r\n\r\nFeature Name : IIS-ISAPIFilter\r\nState : Disabled\r\n\r\nFeature Name : IIS-ServerSideIncludes\r\nState : Disabled\r\n\r\nFeature Name : IIS-CustomLogging\r\nState : Disabled\r\n\r\nFeature Name : IIS-BasicAuthentication\r\nState : Disabled\r\n\r\nFeature Name : IIS-HttpCompressionStatic\r\nState : Disabled\r\n\r\nFeature Name : IIS-ManagementConsole\r\nState : Disabled\r\n\r\nFeature Name : IIS-ManagementService\r\nState : Disabled\r\n\r\nFeature Name : IIS-WMICompatibility\r\nState : Disabled\r\n\r\nFeature Name : IIS-LegacyScripts\r\nState : Disabled\r\n\r\nFeature Name : IIS-LegacySnapIn\r\nState : Disabled\r\n\r\nFeature Name : IIS-FTPServer\r\nState : Disabled\r\n\r\nFeature Name : IIS-FTPSvc\r\nState : Disabled\r\n\r\nFeature Name : IIS-FTPExtensibility\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-Container\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-DCOMProxy\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-Server\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-ADIntegration\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-HTTP\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-Multicast\r\nState : Disabled\r\n\r\nFeature Name : MSMQ-Triggers\r\nState : Disabled\r\n\r\nFeature Name : IIS-CertProvider\r\nState : Disabled\r\n\r\nFeature Name : IIS-WindowsAuthentication\r\nState : Disabled\r\n\r\nFeature Name : IIS-DigestAuthentication\r\nState : Disabled\r\n\r\nFeature Name : IIS-ClientCertificateMappingAuthentication\r\nState : Disabled\r\n\r\nFeature Name : IIS-IISCertificateMappingAuthentication\r\nState : Disabled\r\n\r\nFeature Name : IIS-ODBCLogging\r\nState : Disabled\r\n\r\nFeature Name : MediaPlayback\r\nState : Disabled\r\n\r\nFeature Name : WindowsMediaPlayer\r\nState : Disabled\r\n\r\nFeature Name : DataCenterBridging\r\nState : Disabled\r\n\r\nFeature Name : SmbDirect\r\nState : Disabled\r\n\r\nFeature Name : AppServerClient\r\nState : Disabled\r\n\r\nFeature Name : Printing-PrintToPDFServices-Features\r\nState : Disabled\r\n\r\nFeature Name : Windows-Defender-Default-Definitions\r\nState : Disabled\r\n\r\nFeature Name : Printing-XPSServices-Features\r\nState : Disabled\r\n\r\nFeature Name : MSRDC-Infrastructure\r\nState : Disabled\r\n\r\nFeature Name : TelnetClient\r\nState : Disabled\r\n\r\nFeature Name : NetFx4-AdvSrvs\r\nState : Enabled\r\n\r\nFeature Name : NetFx4Extended-ASPNET45\r\nState : Disabled\r\n\r\nFeature Name : ServicesForNFS-ClientOnly\r\nState : Disabled\r\n\r\nFeature Name : ClientForNFS-Infrastructure\r\nState : Disabled\r\n\r\nFeature Name : NFS-Administration\r\nState : Disabled\r\n\r\nFeature Name : SMB1Protocol-Deprecation\r\nState : Disabled\r\n\r\nFeature Name : MultiPoint-Connector\r\nState : Disabled\r\n\r\nFeature Name : MultiPoint-Connector-Services\r\nState : Disabled\r\n\r\nFeature Name : MultiPoint-Tools\r\nState : Disabled\r\n\r\nFeature Name : SearchEngine-Client-Package\r\nState : Disabled\r\n\r\nFeature Name : TIFFIFilter\r\nState : Disabled\r\n\r\nFeature Name : WorkFolders-Client\r\nState : Disabled\r\n\r\nFeature Name : Printing-Foundation-Features\r\nState : Disabled\r\n\r\nFeature Name : Printing-Foundation-InternetPrinting-Client\r\nState : Disabled\r\n\r\nFeature Name : Printing-Foundation-LPDPrintService\r\nState : Disabled\r\n\r\nFeature Name : Printing-Foundation-LPRPortMonitor\r\nState : Disabled\r\n\r\nFeature Name : MicrosoftWindowsPowerShellV2Root\r\nState : Disabled\r\n\r\nFeature Name : MicrosoftWindowsPowerShellV2\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Windows-Subsystem-Linux\r\nState : Disabled\r\n\r\nFeature Name : HypervisorPlatform\r\nState : Disabled\r\n\r\nFeature Name : VirtualMachinePlatform\r\nState : Disabled\r\n\r\nFeature Name : Client-ProjFS\r\nState : Disabled\r\n\r\nFeature Name : Containers-DisposableClientVM\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-All\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-Tools-All\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-Management-PowerShell\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-Hypervisor\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-Services\r\nState : Disabled\r\n\r\nFeature Name : Microsoft-Hyper-V-Management-Clients\r\nState : Disabled\r\n\r\nFeature Name : HostGuardian\r\nState : Disabled\r\n\r\nFeature Name : Client-DeviceLockdown\r\nState : Disabled\r\n\r\nFeature Name : Client-EmbeddedShellLauncher\r\nState : Disabled\r\n\r\nFeature Name : Client-EmbeddedBootExp\r\nState : Disabled\r\n\r\nFeature Name : Client-EmbeddedLogon\r\nState : Disabled\r\n\r\nFeature Name : Client-KeyboardFilter\r\nState : Disabled\r\n\r\nFeature Name : Client-UnifiedWriteFilter\r\nState : Disabled\r\n\r\nFeature Name : DirectoryServices-ADAM-Client\r\nState : Disabled\r\n\r\nFeature Name : Windows-Defender-ApplicationGuard\r\nState : Disabled\r\n\r\nFeature Name : Containers\r\nState : Disabled\r\n\r\nFeature Name : SMB1Protocol\r\nState : Disabled\r\n\r\nFeature Name : SMB1Protocol-Client\r\nState : Disabled\r\n\r\nFeature Name : SMB1Protocol-Server\r\nState : Disabled\r\n\r\nFeature Name : Internet-Explorer-Optional-amd64\r\nState : Disabled\r\n\r\nThe operation completed successfully.\r\n", "Feature Name : (.+)\\s+State : (.+)", RegexOptions.Multiline))
		{
			Match match = (Match)obj;
			List<Class647> list2 = list;
			Class647 @class = new Class647();
			@class.method_1(match.Groups[1].Value.Trim());
			@class.State = match.Groups[2].Value.Trim();
			list2.Add(@class);
		}
		return list;
	}

	// Token: 0x060017AF RID: 6063 RVA: 0x00064570 File Offset: 0x00062770
	private static string smethod_1(string string_0)
	{
		Process process = new Process();
		process.StartInfo.UseShellExecute = false;
		process.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
		process.StartInfo.CreateNoWindow = true;
		process.StartInfo.RedirectStandardOutput = true;
		process.StartInfo.FileName = "dism";
		process.StartInfo.Arguments = string_0;
		process.Start();
		string result = process.StandardOutput.ReadToEnd();
		process.WaitForExit();
		return result;
	}

	// Token: 0x060017B0 RID: 6064 RVA: 0x000645E8 File Offset: 0x000627E8
	private static string smethod_2(string string_0, string string_1)
	{
		Match match = Regex.Match(string_0, string_1);
		if (!match.Success)
		{
			return null;
		}
		return match.Groups[1].Value.Trim();
	}

	// Token: 0x060017B1 RID: 6065 RVA: 0x00064620 File Offset: 0x00062820
	public static void smethod_3(string string_0)
	{
		Class185.smethod_22("dism /online /disable-feature /featurename:" + string_0 + " /NoRestart");
	}

	// Token: 0x060017B2 RID: 6066 RVA: 0x00064638 File Offset: 0x00062838
	public static void smethod_4(string string_0)
	{
		Class185.smethod_22("dism /online /enable-feature /featurename:" + string_0 + " /NoRestart");
	}

	// Token: 0x060017B3 RID: 6067 RVA: 0x00064650 File Offset: 0x00062850
	public static void smethod_5(string string_0)
	{
		Class185.smethod_22("dism /online /Remove-Package /PackageName:" + string_0 + " /NoRestart");
	}

	// Token: 0x060017B4 RID: 6068 RVA: 0x00064668 File Offset: 0x00062868
	public static bool smethod_6(string string_0)
	{
		string text = string.Empty;
		Process process = new Process();
		process.StartInfo.UseShellExecute = false;
		process.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
		process.StartInfo.CreateNoWindow = true;
		process.StartInfo.RedirectStandardOutput = true;
		process.StartInfo.FileName = "dism";
		process.StartInfo.Arguments = "/online /get-featureinfo /featurename:" + string_0 + " /english";
		process.Start();
		text = process.StandardOutput.ReadToEnd();
		process.WaitForExit();
		return text.ToLower().Contains("state : enabled");
	}

	// Token: 0x060017B5 RID: 6069 RVA: 0x00064704 File Offset: 0x00062904
	internal static List<GClass72> smethod_7(string string_0)
	{
		List<GClass72> list = new List<GClass72>();
		if (Class491.list_0.Contains(string_0))
		{
			list.Add(new GClass72
			{
				String_0 = "Enable",
				List_0 = new List<string>
				{
					"ON",
					"BEST"
				}
			});
			list.Add(new GClass72
			{
				String_0 = "Disable",
				List_0 = new List<string>
				{
					"OFF",
					"DEFAULT"
				}
			});
			return list;
		}
		list.Add(new GClass72
		{
			String_0 = "Disable",
			List_0 = new List<string>
			{
				"OFF",
				"BEST"
			}
		});
		list.Add(new GClass72
		{
			String_0 = "Enable",
			List_0 = new List<string>
			{
				"ON",
				"DEFAULT"
			}
		});
		return list;
	}

	// Token: 0x060017B6 RID: 6070 RVA: 0x00064808 File Offset: 0x00062A08
	internal static string smethod_8(string string_0, GClass179 gclass179_0)
	{
		Class491.Class492 @class = new Class491.Class492();
		@class.string_0 = string_0;
		string a = string.Empty;
		Class647 class2 = Class203.list_0.FirstOrDefault(new Func<Class647, bool>(@class.method_0));
		if (class2 == null || class2 == null)
		{
			return "DISABLED";
		}
		a = class2.State;
		if (a == "Installed" && gclass179_0.method_0())
		{
			return "BEST";
		}
		if (a == "Installed" && !gclass179_0.method_0())
		{
			return "DEFAULT";
		}
		if (a == "Staged" && gclass179_0.method_0())
		{
			return "DEFAULT";
		}
		if (a == "Staged" && !gclass179_0.method_0())
		{
			return "BEST";
		}
		return "DISABLED";
	}

	// Token: 0x040010C9 RID: 4297
	private static List<string> list_0 = new List<string>
	{
		"NetFx4-AdvSrvs",
		"WCF-TCP-PortSharing45",
		"WCF-Services45",
		"NetFx3",
		"BitLocker"
	};

	// Token: 0x040010CA RID: 4298
	public static Dictionary<string, string> dictionary_0 = new Dictionary<string, string>
	{
		{
			"AppServerClient",
			"BEST"
		},
		{
			"BitLocker",
			"BEST"
		},
		{
			"Client-DeviceLockdown",
			"BEST"
		},
		{
			"Client-EmbeddedBootExp",
			"BEST"
		},
		{
			"Client-EmbeddedLogon",
			"BEST"
		},
		{
			"Client-EmbeddedShellLauncher",
			"BEST"
		},
		{
			"Client-KeyboardFilter",
			"BEST"
		},
		{
			"Client-ProjFS",
			"BEST"
		},
		{
			"Client-UnifiedWriteFilter",
			"BEST"
		},
		{
			"ClientForNFS-Infrastructure",
			"BEST"
		},
		{
			"Containers",
			"BEST"
		},
		{
			"Containers-DisposableClientVM",
			"BEST"
		},
		{
			"DataCenterBridging",
			"BEST"
		},
		{
			"DirectoryServices-ADAM-Client",
			"BEST"
		},
		{
			"DirectPlay",
			"DEFAULT"
		},
		{
			"HostGuardian",
			"BEST"
		},
		{
			"HypervisorPlatform",
			"BEST"
		},
		{
			"IIS-ApplicationDevelopment",
			"BEST"
		},
		{
			"IIS-ApplicationInit",
			"BEST"
		},
		{
			"IIS-ASP",
			"BEST"
		},
		{
			"IIS-ASPNET",
			"BEST"
		},
		{
			"IIS-ASPNET45",
			"BEST"
		},
		{
			"IIS-BasicAuthentication",
			"BEST"
		},
		{
			"IIS-CertProvider",
			"BEST"
		},
		{
			"IIS-CGI",
			"BEST"
		},
		{
			"IIS-ClientCertificateMappingAuthentication",
			"BEST"
		},
		{
			"IIS-CommonHttpFeatures",
			"BEST"
		},
		{
			"IIS-CustomLogging",
			"BEST"
		},
		{
			"IIS-DefaultDocument",
			"BEST"
		},
		{
			"IIS-DigestAuthentication",
			"BEST"
		},
		{
			"IIS-DirectoryBrowsing",
			"BEST"
		},
		{
			"IIS-FTPExtensibility",
			"BEST"
		},
		{
			"IIS-FTPServer",
			"BEST"
		},
		{
			"IIS-FTPSvc",
			"BEST"
		},
		{
			"IIS-HealthAndDiagnostics",
			"BEST"
		},
		{
			"IIS-HostableWebCore",
			"BEST"
		},
		{
			"IIS-HttpCompressionDynamic",
			"BEST"
		},
		{
			"IIS-HttpCompressionStatic",
			"BEST"
		},
		{
			"IIS-HttpErrors",
			"BEST"
		},
		{
			"IIS-HttpLogging",
			"BEST"
		},
		{
			"IIS-HttpRedirect",
			"BEST"
		},
		{
			"IIS-HttpTracing",
			"BEST"
		},
		{
			"IIS-IIS6ManagementCompatibility",
			"BEST"
		},
		{
			"IIS-IISCertificateMappingAuthentication",
			"BEST"
		},
		{
			"IIS-IPSecurity",
			"BEST"
		},
		{
			"IIS-ISAPIExtensions",
			"BEST"
		},
		{
			"IIS-ISAPIFilter",
			"BEST"
		},
		{
			"IIS-LegacyScripts",
			"BEST"
		},
		{
			"IIS-LegacySnapIn",
			"BEST"
		},
		{
			"IIS-LoggingLibraries",
			"BEST"
		},
		{
			"IIS-ManagementConsole",
			"BEST"
		},
		{
			"IIS-ManagementScriptingTools",
			"BEST"
		},
		{
			"IIS-ManagementService",
			"BEST"
		},
		{
			"IIS-Metabase",
			"BEST"
		},
		{
			"IIS-NetFxExtensibility",
			"BEST"
		},
		{
			"IIS-NetFxExtensibility45",
			"BEST"
		},
		{
			"IIS-ODBCLogging",
			"BEST"
		},
		{
			"IIS-Performance",
			"BEST"
		},
		{
			"IIS-RequestFiltering",
			"BEST"
		},
		{
			"IIS-RequestMonitor",
			"BEST"
		},
		{
			"IIS-Security",
			"BEST"
		},
		{
			"IIS-ServerSideIncludes",
			"BEST"
		},
		{
			"IIS-StaticContent",
			"BEST"
		},
		{
			"IIS-URLAuthorization",
			"BEST"
		},
		{
			"IIS-WebDAV",
			"BEST"
		},
		{
			"IIS-WebServer",
			"BEST"
		},
		{
			"IIS-WebServerManagementTools",
			"BEST"
		},
		{
			"IIS-WebServerRole",
			"BEST"
		},
		{
			"IIS-WebSockets",
			"BEST"
		},
		{
			"IIS-WindowsAuthentication",
			"BEST"
		},
		{
			"IIS-WMICompatibility",
			"BEST"
		},
		{
			"Internet-Explorer-Optional-amd64",
			"DEFAULT"
		},
		{
			"LegacyComponents",
			"DEFAULT"
		},
		{
			"MediaPlayback",
			"DEFAULT"
		},
		{
			"Microsoft-Hyper-V",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-All",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Hypervisor",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Management-Clients",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Management-PowerShell",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Services",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Tools-All",
			"BEST"
		},
		{
			"Microsoft-RemoteDesktopConnection",
			"BEST"
		},
		{
			"Microsoft-SnippingTool",
			"BEST"
		},
		{
			"Microsoft-Windows-Subsystem-Linux",
			"BEST"
		},
		{
			"MicrosoftWindowsPowerShellV2",
			"DEFAULT"
		},
		{
			"MicrosoftWindowsPowerShellV2Root",
			"DEFAULT"
		},
		{
			"MSMQ-ADIntegration",
			"BEST"
		},
		{
			"MSMQ-Container",
			"BEST"
		},
		{
			"MSMQ-DCOMProxy",
			"BEST"
		},
		{
			"MSMQ-HTTP",
			"BEST"
		},
		{
			"MSMQ-Multicast",
			"BEST"
		},
		{
			"MSMQ-Server",
			"BEST"
		},
		{
			"MSMQ-Triggers",
			"BEST"
		},
		{
			"MSRDC-Infrastructure",
			"DEFAULT"
		},
		{
			"MultiPoint-Connector",
			"BEST"
		},
		{
			"MultiPoint-Connector-Services",
			"BEST"
		},
		{
			"MultiPoint-Tools",
			"BEST"
		},
		{
			"NetFx3",
			"DEFAULT"
		},
		{
			"NetFx4-AdvSrvs",
			"BEST"
		},
		{
			"NetFx4Extended-ASPNET45",
			"BEST"
		},
		{
			"NFS-Administration",
			"BEST"
		},
		{
			"Printing-Foundation-Features",
			"DEFAULT"
		},
		{
			"Printing-Foundation-InternetPrinting-Client",
			"DEFAULT"
		},
		{
			"Printing-Foundation-LPDPrintService",
			"BEST"
		},
		{
			"Printing-Foundation-LPRPortMonitor",
			"BEST"
		},
		{
			"Printing-PrintToPDFServices-Features",
			"DEFAULT"
		},
		{
			"Printing-XPSServices-Features",
			"DEFAULT"
		},
		{
			"SearchEngine-Client-Package",
			"BEST"
		},
		{
			"ServicesForNFS-ClientOnly",
			"BEST"
		},
		{
			"SimpleTCP",
			"BEST"
		},
		{
			"SMB1Protocol",
			"BEST"
		},
		{
			"SMB1Protocol-Client",
			"BEST"
		},
		{
			"SMB1Protocol-Deprecation",
			"BEST"
		},
		{
			"SMB1Protocol-Server",
			"BEST"
		},
		{
			"SmbDirect",
			"DEFAULT"
		},
		{
			"TelnetClient",
			"BEST"
		},
		{
			"TFTP",
			"BEST"
		},
		{
			"TIFFIFilter",
			"BEST"
		},
		{
			"VirtualMachinePlatform",
			"BEST"
		},
		{
			"WAS-ConfigurationAPI",
			"BEST"
		},
		{
			"WAS-NetFxEnvironment",
			"BEST"
		},
		{
			"WAS-ProcessModel",
			"BEST"
		},
		{
			"WAS-WindowsActivationService",
			"BEST"
		},
		{
			"WCF-HTTP-Activation",
			"BEST"
		},
		{
			"WCF-HTTP-Activation45",
			"BEST"
		},
		{
			"WCF-MSMQ-Activation45",
			"BEST"
		},
		{
			"WCF-NonHTTP-Activation",
			"BEST"
		},
		{
			"WCF-Pipe-Activation45",
			"BEST"
		},
		{
			"WCF-Services45",
			"BEST"
		},
		{
			"WCF-TCP-Activation45",
			"BEST"
		},
		{
			"WCF-TCP-PortSharing45",
			"BEST"
		},
		{
			"Windows-Defender-ApplicationGuard",
			"BEST"
		},
		{
			"Windows-Identity-Foundation",
			"BEST"
		},
		{
			"WindowsMediaPlayer",
			"DEFAULT"
		},
		{
			"WorkFolders-Client",
			"DEFAULT"
		}
	};

	// Token: 0x040010CB RID: 4299
	public static Dictionary<string, string> dictionary_1 = new Dictionary<string, string>
	{
		{
			"TFTP",
			"BEST"
		},
		{
			"LegacyComponents",
			"BEST"
		},
		{
			"DirectPlay",
			"DEFAULT"
		},
		{
			"SimpleTCP",
			"BEST"
		},
		{
			"Windows-Identity-Foundation",
			"BEST"
		},
		{
			"NetFx3",
			"BEST"
		},
		{
			"WCF-HTTP-Activation",
			"BEST"
		},
		{
			"WCF-NonHTTP-Activation",
			"BEST"
		},
		{
			"IIS-WebServerRole",
			"BEST"
		},
		{
			"IIS-WebServer",
			"BEST"
		},
		{
			"IIS-CommonHttpFeatures",
			"BEST"
		},
		{
			"IIS-HttpErrors",
			"BEST"
		},
		{
			"IIS-HttpRedirect",
			"BEST"
		},
		{
			"IIS-ApplicationDevelopment",
			"BEST"
		},
		{
			"IIS-Security",
			"BEST"
		},
		{
			"IIS-RequestFiltering",
			"BEST"
		},
		{
			"IIS-NetFxExtensibility",
			"BEST"
		},
		{
			"IIS-NetFxExtensibility45",
			"BEST"
		},
		{
			"IIS-HealthAndDiagnostics",
			"BEST"
		},
		{
			"IIS-HttpLogging",
			"BEST"
		},
		{
			"IIS-LoggingLibraries",
			"BEST"
		},
		{
			"IIS-RequestMonitor",
			"BEST"
		},
		{
			"IIS-HttpTracing",
			"BEST"
		},
		{
			"IIS-URLAuthorization",
			"BEST"
		},
		{
			"IIS-IPSecurity",
			"BEST"
		},
		{
			"IIS-Performance",
			"BEST"
		},
		{
			"IIS-HttpCompressionDynamic",
			"BEST"
		},
		{
			"IIS-WebServerManagementTools",
			"BEST"
		},
		{
			"IIS-ManagementScriptingTools",
			"BEST"
		},
		{
			"IIS-IIS6ManagementCompatibility",
			"BEST"
		},
		{
			"IIS-Metabase",
			"BEST"
		},
		{
			"WAS-WindowsActivationService",
			"BEST"
		},
		{
			"WAS-ProcessModel",
			"BEST"
		},
		{
			"WAS-NetFxEnvironment",
			"BEST"
		},
		{
			"WAS-ConfigurationAPI",
			"BEST"
		},
		{
			"IIS-HostableWebCore",
			"BEST"
		},
		{
			"WCF-Services45",
			"BEST"
		},
		{
			"WCF-HTTP-Activation45",
			"BEST"
		},
		{
			"WCF-TCP-Activation45",
			"BEST"
		},
		{
			"WCF-Pipe-Activation45",
			"BEST"
		},
		{
			"WCF-MSMQ-Activation45",
			"BEST"
		},
		{
			"WCF-TCP-PortSharing45",
			"BEST"
		},
		{
			"IIS-StaticContent",
			"BEST"
		},
		{
			"IIS-DefaultDocument",
			"BEST"
		},
		{
			"IIS-DirectoryBrowsing",
			"BEST"
		},
		{
			"IIS-WebDAV",
			"BEST"
		},
		{
			"IIS-WebSockets",
			"BEST"
		},
		{
			"IIS-ApplicationInit",
			"BEST"
		},
		{
			"IIS-ASPNET",
			"BEST"
		},
		{
			"IIS-ASPNET45",
			"BEST"
		},
		{
			"IIS-ASP",
			"BEST"
		},
		{
			"IIS-CGI",
			"BEST"
		},
		{
			"IIS-ISAPIExtensions",
			"BEST"
		},
		{
			"IIS-ISAPIFilter",
			"BEST"
		},
		{
			"IIS-ServerSideIncludes",
			"BEST"
		},
		{
			"IIS-CustomLogging",
			"BEST"
		},
		{
			"IIS-BasicAuthentication",
			"BEST"
		},
		{
			"IIS-HttpCompressionStatic",
			"BEST"
		},
		{
			"IIS-ManagementConsole",
			"BEST"
		},
		{
			"IIS-ManagementService",
			"BEST"
		},
		{
			"IIS-WMICompatibility",
			"BEST"
		},
		{
			"IIS-LegacyScripts",
			"BEST"
		},
		{
			"IIS-LegacySnapIn",
			"BEST"
		},
		{
			"IIS-FTPServer",
			"BEST"
		},
		{
			"IIS-FTPSvc",
			"BEST"
		},
		{
			"IIS-FTPExtensibility",
			"BEST"
		},
		{
			"MSMQ-Container",
			"BEST"
		},
		{
			"MSMQ-DCOMProxy",
			"BEST"
		},
		{
			"MSMQ-Server",
			"BEST"
		},
		{
			"MSMQ-ADIntegration",
			"BEST"
		},
		{
			"MSMQ-HTTP",
			"BEST"
		},
		{
			"MSMQ-Multicast",
			"BEST"
		},
		{
			"MSMQ-Triggers",
			"BEST"
		},
		{
			"IIS-CertProvider",
			"BEST"
		},
		{
			"IIS-WindowsAuthentication",
			"BEST"
		},
		{
			"IIS-DigestAuthentication",
			"BEST"
		},
		{
			"IIS-ClientCertificateMappingAuthentication",
			"BEST"
		},
		{
			"IIS-IISCertificateMappingAuthentication",
			"BEST"
		},
		{
			"IIS-ODBCLogging",
			"BEST"
		},
		{
			"MediaPlayback",
			"DEFAULT"
		},
		{
			"WindowsMediaPlayer",
			"DEFAULT"
		},
		{
			"DataCenterBridging",
			"BEST"
		},
		{
			"SmbDirect",
			"BEST"
		},
		{
			"AppServerClient",
			"BEST"
		},
		{
			"Printing-PrintToPDFServices-Features",
			"DEFAULT"
		},
		{
			"Printing-XPSServices-Features",
			"DEFAULT"
		},
		{
			"SearchEngine-Client-Package",
			"BEST"
		},
		{
			"MSRDC-Infrastructure",
			"BEST"
		},
		{
			"Microsoft-SnippingTool",
			"BEST"
		},
		{
			"TelnetClient",
			"BEST"
		},
		{
			"TIFFIFilter",
			"BEST"
		},
		{
			"WorkFolders-Client",
			"BEST"
		},
		{
			"Printing-Foundation-Features",
			"DEFAULT"
		},
		{
			"Printing-Foundation-InternetPrinting-Client",
			"DEFAULT"
		},
		{
			"Printing-Foundation-LPDPrintService",
			"BEST"
		},
		{
			"Printing-Foundation-LPRPortMonitor",
			"BEST"
		},
		{
			"MicrosoftWindowsPowerShellV2Root",
			"BEST"
		},
		{
			"MicrosoftWindowsPowerShellV2",
			"BEST"
		},
		{
			"Client-ProjFS",
			"BEST"
		},
		{
			"Client-DeviceLockdown",
			"BEST"
		},
		{
			"Client-EmbeddedShellLauncher",
			"BEST"
		},
		{
			"Client-EmbeddedBootExp",
			"BEST"
		},
		{
			"Client-EmbeddedLogon",
			"BEST"
		},
		{
			"Client-KeyboardFilter",
			"BEST"
		},
		{
			"Client-UnifiedWriteFilter",
			"BEST"
		},
		{
			"NetFx4-AdvSrvs",
			"BEST"
		},
		{
			"NetFx4Extended-ASPNET45",
			"BEST"
		},
		{
			"ServicesForNFS-ClientOnly",
			"BEST"
		},
		{
			"ClientForNFS-Infrastructure",
			"BEST"
		},
		{
			"NFS-Administration",
			"BEST"
		},
		{
			"SMB1Protocol",
			"BEST"
		},
		{
			"SMB1Protocol-Client",
			"BEST"
		},
		{
			"SMB1Protocol-Server",
			"BEST"
		},
		{
			"SMB1Protocol-Deprecation",
			"BEST"
		},
		{
			"HostGuardian",
			"BEST"
		},
		{
			"MultiPoint-Connector",
			"BEST"
		},
		{
			"MultiPoint-Connector-Services",
			"BEST"
		},
		{
			"MultiPoint-Tools",
			"BEST"
		},
		{
			"Internet-Explorer-Optional-amd64",
			"DEFAULT"
		},
		{
			"Microsoft-RemoteDesktopConnection",
			"BEST"
		},
		{
			"Microsoft-Windows-Subsystem-Linux",
			"BEST"
		},
		{
			"HypervisorPlatform",
			"BEST"
		},
		{
			"VirtualMachinePlatform",
			"BEST"
		},
		{
			"Containers-DisposableClientVM",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-All",
			"BEST"
		},
		{
			"Microsoft-Hyper-V",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Tools-All",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Management-PowerShell",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Hypervisor",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Services",
			"BEST"
		},
		{
			"Microsoft-Hyper-V-Management-Clients",
			"BEST"
		},
		{
			"DirectoryServices-ADAM-Client",
			"BEST"
		},
		{
			"Windows-Defender-ApplicationGuard",
			"BEST"
		},
		{
			"Containers",
			"BEST"
		},
		{
			"BitLocker",
			"BEST"
		}
	};

	// Token: 0x040010CC RID: 4300
	public static List<string> list_1 = new List<string>
	{
		"NetFx3",
		"NetFx4-AdvSrvs",
		"LegacyComponents",
		"Internet-Explorer-Optional-amd64",
		"MediaPlayback",
		"MicrosoftWindowsPowerShellV2Root",
		"Printing-Foundation-Features",
		"Printing-Foundation-InternetPrinting-Client",
		"Printing-PrintToPDFServices-Features",
		"Printing-XPSServices-Features",
		"SmbDirect",
		"WorkFolders-Client"
	};

	// Token: 0x02000434 RID: 1076
	private sealed class Class492
	{
		// Token: 0x060017B8 RID: 6072 RVA: 0x000648EC File Offset: 0x00062AEC
		internal bool method_0(Class647 class647_0)
		{
			return class647_0.method_0() == this.string_0;
		}

		// Token: 0x040010CD RID: 4301
		public string string_0;
	}
}
